services:
  - type: web
    name: infera-web
    env: docker
    plan: free
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: NEXT_PUBLIC_SUPABASE_URL
        sync: false
      - key: NEXT_PUBLIC_SUPABASE_ANON_KEY
        sync: false
      - key: NEXT_PUBLIC_SITE_URL
        value: https://infera.onrender.com
      - key: VERCEL_ANALYTICS_ID
        sync: false
      - key: GOOGLE_SITE_VERIFICATION
        sync: false
    healthCheckPath: /api/health
    autoDeploy: true
    branch: master
    rootDir: .
    dockerfilePath: ./Dockerfile
