services:
  - type: web
    name: infera-web
    env: node
    plan: free
    buildCommand: npm install && npm run build
    startCommand: npm start
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 10000
      - key: VERCEL_ANALYTICS_ID
        sync: false
      - key: SITE_URL
        value: https://infera.onrender.com
      - key: GOOGLE_SITE_VERIFICATION
        sync: false
    healthCheckPath: /api/health
    autoDeploy: true
    branch: master
    rootDir: .
    dockerfilePath: ./Dockerfile
